# version: "3"
# services:
#   web:
#     build: ./client
#     ports:
#       - "8000:3000"
#     links:
#       - node
#   node:
#     build: .././favouritrbtn
#     ports:
#       - "2000:5000"
#     links:
#       - mongo
#   mongo:
#     image: mongo
#     ports:
#       - "27017:27017"

version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: shadan
      MONGO_INITDB_ROOT_PASSWORD: shadan123
  backend:
    build: .././favouritrbtn
    image: shadan/backend
    ports:
      - "5000:5000"
    volumes:
      - .././favouritrbtn:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: ./client
    image: shadan/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - backend
